#!/bin/bash

python export_inference_graph.py --input_type image_tensor --pipeline_config_path training/faster_rcnn_inception_v2_pets.config --trained_checkpoint_prefix model/model.ckpt-$1 --output_directory inference_graph